package gui;

import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import rmi.EquationData;
import rmi.IRemoteServer;

public class Main extends javax.swing.JFrame {

    private Registry registry = null;
    private IRemoteServer remoteServer = null;

    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldServerName = new javax.swing.JTextField();
        jLabelY = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldX = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldA = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButtonSolve = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldB = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldServerAddress = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldServerPort = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GVS03_RMI_Client_Server");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/example.png"))); // NOI18N
        jLabel1.setAlignmentY(0.0F);
        jLabel1.setFocusable(false);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jTextFieldServerName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldServerName.setText("solver");
        getContentPane().add(jTextFieldServerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, 180, -1));

        jLabelY.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelY.setText("Y =");
        getContentPane().add(jLabelY, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 220, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("X =");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 30, -1));

        jTextFieldX.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(jTextFieldX, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 90, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("A =");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 30, -1));

        jTextFieldA.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(jTextFieldA, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 90, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Имя:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, -1, -1));

        jButtonSolve.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSolve.setText("Решить");
        jButtonSolve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSolveActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSolve, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 220, 30));

        jButtonClear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonClear.setText("Очистить");
        jButtonClear.setMaximumSize(new java.awt.Dimension(87, 25));
        jButtonClear.setMinimumSize(new java.awt.Dimension(87, 25));
        jButtonClear.setPreferredSize(new java.awt.Dimension(87, 25));
        jButtonClear.setRequestFocusEnabled(false);
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, 220, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("B =");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 30, -1));

        jTextFieldB.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(jTextFieldB, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 90, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Адрес сервера:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 120, -1));

        jTextFieldServerAddress.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldServerAddress.setText("localhost");
        getContentPane().add(jTextFieldServerAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 110, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Порт:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, -1, -1));

        jTextFieldServerPort.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldServerPort.setText("1099");
        getContentPane().add(jTextFieldServerPort, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 60, -1));

        setSize(new java.awt.Dimension(622, 410));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        jTextFieldX.setText("");
        jTextFieldA.setText("");
        jTextFieldServerName.setText("");
        jLabelY.setText("Y =");
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jButtonSolveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSolveActionPerformed
        try {
            String serverAddress = jTextFieldServerAddress.getText();
            int serverPort = Integer.parseInt(jTextFieldServerPort.getText());
            String serverName = jTextFieldServerName.getText();

            if (registry == null || remoteServer == null) {
                System.out.println("Connecting...");
                registry = LocateRegistry.getRegistry(serverAddress, serverPort);
                remoteServer = (IRemoteServer) registry.lookup(serverName);
                System.out.println("Connected to //" + serverAddress + ":" + serverPort + "/" + serverName);
            }

            double x = Double.parseDouble(jTextFieldX.getText());
            double secondArgument;
            if (x <= 4) {
                secondArgument = Double.parseDouble(jTextFieldA.getText());
            } else {
                secondArgument = Double.parseDouble(jTextFieldB.getText());
            }
            EquationData data = new EquationData(x, secondArgument);
            data = remoteServer.solveEquation(data);

            jLabelY.setText("Y = " + data.getY());

        } catch (Exception e) {
            e.printStackTrace();
            jLabelY.setText("ОШИБКА");
        }
    }//GEN-LAST:event_jButtonSolveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonSolve;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelY;
    private javax.swing.JTextField jTextFieldA;
    private javax.swing.JTextField jTextFieldB;
    private javax.swing.JTextField jTextFieldServerAddress;
    private javax.swing.JTextField jTextFieldServerName;
    private javax.swing.JTextField jTextFieldServerPort;
    private javax.swing.JTextField jTextFieldX;
    // End of variables declaration//GEN-END:variables
}
